spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.h2.Driver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sa
    password:

  # JAP 설정
  jpa:
    properties:
      hibernate:
        # 실행되는 쿼리를 콘솔에 출력
        show_sql: true
        # 콘솔 창에 출력되는 쿼리 정렬
        format_sql: true
        use_sql_comments: true
        # DB 플랫폼 설정??
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace